import random
#random variable generated by the computer stored in varaiable computer_number 
computer_number = random.randrange(0, 100)

#initlise guess with False
guessed = False
#guess counter
GuessCounter = 0

while True: 
    if not guessed:
        answer = input ("Guess the number, it is betwee 0 and 100:")
        GuessCounter += 1
        if int(answer) == computer_number:
            guessed = True
            print("You got it!")
            break
        elif int(answer) > computer_number:
            print("Too high, try again.")
        else:
            print("Too low, try again.")
    else: 
        break
print(f"You made {GuessCounter} guesses.")



           
        

